[package]
name = "berry-pasty"
version = "0.1.0"
edition = "2021"
authors = ["GZTime <Time.GZ@outlook.com>"]

[dependencies]
serde = "1.0"
redb = "2.1"
nanoid = "0.4"
url = "2.2"
rocket = "0.5"
anyhow = "1.0"
chrono = "0.4"
paste = "1.0"

[profile.release]
opt-level = 3
strip = true
lto = "thin"
